W5D1/music/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resources :bands, only: [:index, :new, :create, :edit, :show]
  resource :session, only: [:new, :create, :destroy]

end

W5D1/music/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :string           not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  
end

W5D1/music/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

W5D1/music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  private

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end
end

W5D1/music/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def show
    @band = Band.find_by(params[:id])
    redirect_to band_url(@band)
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      render :index
    else
      flash.now[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def edit

  end


  private
  def band_params
    params.require(:band).permit(:name)
  end
end

W5D1/music/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if user.nil?
      flash.now[:errors] = ["Incorrect email/password combo"]
    else
      login(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

W5D1/music/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      render :show
    else
      flash.now[:errors] = @user.errors.full_messages
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W5D1/music/app/views/bands/index.html.erb
<a href="<%= new_band_url %>">Add a band</a>
<%= render @bands %>

W5D1/music/app/views/bands/new.html.erb
<h1>Create a band</h1>
<form action="<%= bands_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  Name
  <br>
  <input type="text" name="band[name]">
  <br>

  <input type="submit" value="Let's rock">
</form>

W5D1/music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>


  <header>
    <div class="row">
      <div class="col1"></div>
      <div class="col2">Musica</div>
      <div class="col3">
        <% if current_user %>
        <%= button_to("Logout", session_url, method: :delete) %>
        <% else %>
        <div>
          <a href="<%= new_session_url %>">Login</a>
          <br><br>
          <a href="<%= new_user_url %>">Signup</a>
        </div>

        <% end %>
      </div>
    </div>
</header>



  <body>
    <%= yield %>
  </body>
</html>

W5D1/music/app/views/users/new.html.erb
<h1>Signup</h1>
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  Email
  <br>
  <input type="text" name="user[email]">
  <br>
  Password
  <br>
  <input placeholder="> 5 characters" type="password" name="user[password]">
  <br>
  <input type="submit" value="Signup">
</form>

W5D1/music/app/views/users/show.html.erb
<%= @user.email %>